#!/usr/bin/env bash
set -euo pipefail

# -------------------------------------------------
# rearrange.sh – reorganise the wazuh‑docker‑stack repo
# -------------------------------------------------
# This script creates a professional directory layout and moves
# existing files into their new locations.
# It is safe to run multiple times – it will only create missing
# directories and move files that still reside in the old places.

# 1. Create target directories
mkdir -p scripts
mkdir -p single-node/config/wazuh_dashboard
mkdir -p single-node/config/wazuh_indexer/ssl_certs
mkdir -p logs
mkdir -p docs

# 2. Move files (ignore errors if they are already moved)
mv -v upgrade_all.sh scripts/ || true
mv -v single-node/docker-compose.yml single-node/ || true
mv -v single-node/config/wazuh_manager.conf single-node/config/ || true
mv -v single-node/config/wazuh_dashboard/wazuh.yml single-node/config/wazuh_dashboard/ || true
mv -v single-node/config/wazuh_dashboard/opensearch_dashboards.yml single-node/config/wazuh_dashboard/ || true
mv -v single-node/config/wazuh_indexer/wazuh.indexer.yml single-node/config/wazuh_indexer/ || true
# Move any existing SSL certs (if the old folder still exists)
if [ -d "single-node/config/wazuh_indexer_ssl_certs" ]; then
  mv -v single-node/config/wazuh_indexer_ssl_certs/* single-node/config/wazuh_indexer/ssl_certs/ || true
  rmdir single-node/config/wazuh_indexer_ssl_certs || true
fi

# 3. Create a basic .gitignore (overwrites if present)
cat > .gitignore <<'EOF'
# Logs
logs/*.log

# SSL certificates – keep them out of the repository
single-node/config/**/ssl_certs/*

# Temporary files
*.tmp
*.bak
EOF

# 4. Add a starter README (overwrites if present)
cat > README.md <<'EOF'
# Wazuh Docker Stack

A single‑node deployment of the Wazuh security platform using Docker‑Compose.

## Directory layout
```
📁 scripts/                # Helper scripts (upgrade_all.sh, rearrange.sh)
📁 single-node/            # Docker‑Compose stack and configuration
│   ├─ docker-compose.yml
│   └─ config/
│       ├─ wazuh_manager.conf
│       ├─ wazuh_dashboard/
│       │   ├─ wazuh.yml
│       │   └─ opensearch_dashboards.yml
│       └─ wazuh_indexer/
│           ├─ wazuh.indexer.yml
│           └─ ssl_certs/   # TLS certificates (git‑ignored)
📁 logs/                   # Runtime logs (upgrade_all.log)
📁 docs/                   # Documentation, diagrams, etc.
```

## Prerequisites
```bash
sudo apt-get update && sudo apt-get install -y \
    docker docker-compose sshpass curl
```

## Quick start
```bash
# Make scripts executable
chmod +x scripts/*.sh

# Run the upgrade script (it will pull and restart Pi‑hole & Mitmproxy)
bash scripts/upgrade_all.sh
```

## CI pipeline
A GitHub Actions workflow runs `shellcheck` on all shell scripts and executes a dry‑run of `upgrade_all.sh`.

---
Generated by Antigravity AI.
EOF

# 5. Create a simple CI workflow (GitHub Actions)
mkdir -p .github/workflows
cat > .github/workflows/ci.yml <<'EOF'
name: CI
on: [push, pull_request]
jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install shellcheck
        run: sudo apt-get update && sudo apt-get install -y shellcheck
      - name: Lint scripts
        run: |
          shellcheck scripts/*.sh
      - name: Dry‑run upgrade script
        env:
          UPGRADE_PASSWORD: dummy
          UPGRADE_HOST: localhost
        run: |
          bash scripts/upgrade_all.sh --dry-run || true
EOF

echo "✅ Project re‑organisation files created."
